### ISSUE TITLE
our case is very inconsistent

### ISSUE THREAD

**Issue by fcbond** [singdict/SingDict#5]
Maybe we should default to lower case, and only be upper if it is a proper noun?

A look at the tail:
> terbalik.jsonl
> tofu.jsonl
> Tolong.jsonl
> Tong tong.jsonl
> Tudung.jsonl
> Tzap.jsonl
> Uncle.jsonl
> what.jsonl
> wor.jsonl
> Yong tau foo.jsonl

**Comment by siewyeng** [comment]
to lowercase everything by default

**Comment by siewyeng** [comment]
This has also been completed in the new "Lexicon" tab with a custom formula in column A `=IF(ISNUMBER('Lexicon-original'!A1), 'Lexicon-original'!A1, IF(REGEXMATCH('Lexicon-original'!A1, "^[A-Z][A-Z]"), 'Lexicon-original'!A1, LOWER('Lexicon-original'!A1)))`

This seems to work well except for the entry "A&E" which I have changed manually.
